name: Auto Release

on:
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: npm ci

            - name: Check if release is needed
              id: check_version
              run: |
                  LOCAL_VERSION=$(node -p "require('./package.json').version")
                  PACKAGE_NAME=$(node -p "require('./package.json').name")
                  NPM_VERSION=$(npm view $PACKAGE_NAME version || echo "0.0.0")

                  echo "Local version: $LOCAL_VERSION"
                  echo "Published NPM version: $NPM_VERSION"

                  # Use npx semver to compare and store result
                  RELEASE_NEEDED=$(npx semver "$LOCAL_VERSION" --range ">$NPM_VERSION" || echo "")

                  if [ -n "$RELEASE_NEEDED" ]; then
                    echo "should_release=true" >> $GITHUB_ENV
                  else
                    echo "should_release=false" >> $GITHUB_ENV
                  fi

            - name: Check Formatting
              if: env.should_release == 'true'
              run: npm run format:check

            - name: Run Linter
              if: env.should_release == 'true'
              run: npm run lint

            - name: Check typings
              if: env.should_release == 'true'
              run: npm run typecheck

            - name: Run tests
              if: env.should_release == 'true'
              run: npm run test

            - name: Build project
              if: env.should_release == 'true'
              run: npm run build

            - name: Publish via OIDC
              if: env.should_release == 'true'
              run: npm publish --provenance --access public
